### ISSUE TITLE
Fail Handling need to improve

### ISSUE THREAD

**Issue by sandunisuru** [Sandun-Isuru-Niraj/Video-Master-Backend#4]
There is some bug when trying to get some videos the server fails and not restarted. Specially in the extension.

**Comment by jisack** [comment]
as i see it stuck with your cors origin server block or you have to make your client to access via `https`
![image](https://user-images.githubusercontent.com/16641152/67257175-f7c9d100-f4b4-11e9-8d61-4f521b39114b.png)

**Comment by sandunisuru** [comment]
This solves by #5 pull request. So I'm closing this.
